spring:
  datasource:
    url: jdbc:mariadb:mariadb:3306/test
    username: root
    password: codesoom
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: "12345678901234567890123456789010"
