spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: "12345678901234567890123456789010"

---
# "mariadb" Profile을 쓸 때...
spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: password